
services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - /home/ildar/larastart/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/ildar/larastart/src:/var/www/laravel
    depends_on:
      - mysql
      - php
  php:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - /home/ildar/larastart/src:/var/www/laravel
  mysql:
    image: mysql:8.0
    ports:
      - "3316:3306"
    env_file:
      - env/mysql.env
    volumes:
      - /home/ildar/larastart/mysql/db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8888:80"
    environment:
      - PMA_ARBITRARY=1


  composer:
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - /home/ildar/larastart/src:/var/www/laravel
  artisan:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - /home/ildar/larastart/src:/var/www/laravel
    entrypoint: ["php", "/var/www/laravel/artisan"]

